### PR TITLE
newest database update

### PR DESCRIPTION
**Pull request by AkilaDee**

### CODE REVIEW

**Comment by dumidu1998** [comment]
lines delete krda? SQL file eke?

**Comment by dumidu1998** [comment]
@AkilaDee

**Comment by AkilaDee** [comment]
thibuna eka delete krla aluth eka paste kra

**Comment by dumidu1998** [comment]
@AkilaDee  vegetable table ek wtri export wel tyne. Hriyt export wela na. aye export krl paste krnn. DB ekama export krnn. table ekk ine ntuw db name ek uda click krl export krnna

**Pull request closed without merging**
